# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Manual Workflow Trigger
on:
  workflow_dispatch:  
    inputs:
      CN:
        description: 'CN'
        type: string
        required: true
      O:
        description: 'O'
        type: string
        default: 'latest'
      FriendlyName:
        description: 'Perform a dry run?'
        type: string
        default: Certificate
jobs:    
  build:
    runs-on: windows-latest
    env:
      thumb: ""
    steps:
    - name: CreateCertificate
      run: New-SelfSignedCertificate -Type Custom -KeyUsage DigitalSignature -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}") -Subject "CN= ${{github.event.inputs.CN}} , O=Contoso Corporation, C=US" -FriendlyName "Your friendly name goes here"
    
    - name: Thumbprint
      run: ${{env.thumb}} = (Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object {$_.Subject -match "CN=${{github.event.inputs.CN}}"}).thumbprint
    - name: UploadCertificate
      uses: actions/upload-artifact@v5.0.0
      with:
        name: WinCert
        path: .\**\*.pfx*

        retention-days: 15
