# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Manual Workflow Trigger
on:
  workflow_dispatch:
    inputs:
      CN:
        description: 'CN'
        type: string
        required: true
      O:
        description: 'O'
        type: string
        default: 'latest'
      FriendlyName:
        description: 'Perform a dry run?'
        type: string
        default: Certificate
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: CreateCertificate
      run: New-SelfSignedCertificate -Type Custom -KeyUsage DigitalSignature -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}") -Subject "CN= ${{github.event.inputs.version}} , O=Contoso Corporation, C=US" -FriendlyName "Your friendly name goes here"
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
